project_name: risk_analysis
loglevel: info
analyses:
  - analysis_name: full_java_check
    source_directory: src
    only_permit_languages:
      - java
    only_permit_file_extensions:
      - .java
    file_scan:
      - number_of_methods
      - source_lines_of_code
      - dependency_graph
      - fan_in_out
      - louvain_modularity
      - tfidf
    entity_scan:
      - dependency_graph
      - source_lines_of_code
      - number_of_methods
      - fan_in_out
      - louvain_modularity
      - tfidf
export:
  - directory: emerge_output
    formats:
      - graphml
      - json
      - tabular_file
      - tabular_console_overall
      - d3
